### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by zakj** [lektor/lektor-webpack-support#10]
Would you be open to a PR adding support for using [`yarn`](https://yarnpkg.com/) in place of `npm install`? It both runs faster and uses a lockfile (for package version pinning). The implementation I have in mind would [rename and] update `npm_install()` to check for a `yarn` executable and a `.../webpack/yarn.lock` file, using `yarn` in that case or defaulting to current behavior.

**Comment by singingwolfboy** [comment]
That makes perfect sense to me. Go for it!
