### ISSUE TITLE
(Newbie) problems following install instructions

### ISSUE THREAD

**Issue by obestwalter** [lektor/lektor-webpack-support#11]
Hi @mitsuhiko and @singingwolfboy thanks for all the work you do on lektor.

Disclaimer: I am new to lektor and also webpack.

When I follow the installation instructions I have two problems:

#### `package.json` not complete

    npm install --save-dev webpack babel-core node-sass babel-loader sass-loader css-loader url-loader style-loader file-loader extract-text-webpack-plugin 
    npm ERR! addLocal Could not install /home/oliver/work/oliver.bestwalter.de/lektor/webpack
    npm ERR! Linux 4.8.13-1-ARCH
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save-dev" "webpack" "babel-core" "node-sass" "babel-loader" "sass-loader" "css-loader" "url-loader" "style-loader" "file-loader" "extract-text-webpack-plugin"
    npm ERR! node v7.3.0
    npm ERR! npm  v4.0.5

    npm ERR! No name provided in package.json
    npm ERR! 
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/oliver/work/oliver.bestwalter.de/lektor/npm-debug.log

Adding a name key to `package.json` then leads to the next error that a version is mising. If I add that also everything works fine. I am guessing that this changed at some point and the fields were made mandatory? The current [docs](https://docs.npmjs.com/getting-started/using-a-package.json#requirements) look that way.

So my guess would be that the README needs to be changed to something like this:

    {
      "name": "lektor-project-webpack",
      "version": "1.0.0",
      "private": true
    }

#### npm needs to be run inside webpack folder

As a newbie to lektor and webpack I naively expected everything to work if I run the commands from the lektor project, but the npm command needs to be run from inside the webpack folder.

**Comment by obestwalter** [comment]
Updated issue and PR after learning more about webpack.

**Comment by mitsuhiko** [comment]
Interesting. This did not used to be an error in the past just a warning.
